name: CI/CD Pipeline para ToDoList

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      APP_URL: ${{ secrets.APP_URL }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Imprimir variables de entorno
        run: |
          echo "DB_USER: $DB_USER"
          echo "DB_HOST: $DB_HOST"

      - name: Ejecutar pruebas
        run: |
          npm install -g jest
          jest --no-cache --detectOpenHandles --forceExit
        env:
          NODE_OPTIONS: --experimental-vm-modules

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Desplegar en Railway
        run: railway up --service APIToDoList
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Validar despliegue
        run: |
          sleep 30
          curl ${{ secrets.APP_URL }}/api/todos
